version: "3"

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5000:5000
    restart: always
