name: Deploy to application server
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull, build, and deploy
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          debug: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /usr/local/containers/${{ secrets.CONTAINER_NAME }}
            git pull
            docker-compose build
            docker-compose down
            docker-compose up -d
            docker image prune -f
